---
- name: "Download, verify, mount install images for '{{ distro }}'"
  hosts: netinstall
  tasks:
  - name: "Cleanup pxe repo"
    block:
    - name: "Find used pxe repo directories"
      tags: 
      - finds
      - umount
      - config
      find:
        file_type: directory
        follow: yes
        paths: "{{ pxe_dir }}/{{ distro }}"
      register: _find
    - name: "Umount '{{ os | selectattr('name','==',distro) | map(attribute='description') | list | first }}' pxe"
      tags: umount
      mount:
        path: "{{ item }}"
        state: umounted
      loop: "{{ _find['files'] | map(attribute='path') | list | difference( os | selectattr('name','eq',distro) | list | subelements('release') | flatten | selectattr('version','defined') | map(attribute='version') | list | map('regex_replace','^', pxe_dir +'/'+ distro +'/') | list) }}"
      when: item[0]['name'] != 'solaris'
    - name: "Remove unused pxe fstab entries"
      tags: config
      replace:
        path: /etc/fstab
        regexp: "{{ item }}"
      loop: "{{ _find['files'] | map(attribute='path') | list | difference( os | selectattr('name','eq',distro) | list | subelements('release') | flatten | selectattr('version','defined') | map(attribute='version') | list | map('regex_replace','^', pxe_dir +'/'+ distro +'/') | list) }}"

  - name: "Cleanup pkg repo"
    block:
    - name: "Find used pkg repo directories"
      tags: 
      - find
      - umount
      - config
      find:
        file_type: directory
        follow: yes
        paths: "{{ os | selectattr('name','==',distro) | map(attribute='repo_dir') | list | first }}"
      register: _find
    - name: "Umount '{{ os | selectattr('name','==',distro) | map(attribute='description') | list | first }}' pkg"
      tags: umount
      mount:
        path: "{{ item }}"
        state: umounted
      loop: "{{ _find['files'] | map(attribute='path') | list | difference(os | selectattr('name','eq',distro) | list | map(attribute='repo_dir') | product(os | selectattr('name','eq',distro) | list | subelements('release') | flatten | selectattr('version','defined') | map(attribute='version') | list) | map('join','/') | list) }}"
      when: item[0]['name'] != 'solaris'
    - name: "Remove unused pxe fstab entries"
      tags: config
      replace:
        path: /etc/fstab
        regexp: "{{ item }}"
      loop: "{{ _find['files'] | map(attribute='path') | list | difference(os | selectattr('name','eq',distro) | list | map(attribute='repo_dir') | product(os | selectattr('name','eq',distro) | list | subelements('release') | flatten | selectattr('version','defined') | map(attribute='version') | list) | map('join','/') | list) }}"
