---
- name: "Create PXE configuration files"
  hosts: netinstall
  vars:
  - pxe_kickstart: pxe-kickstart.ji2
  tasks:
  - name: "Create PXE menu files for each distribution"
    tags: menu
    template:
      src: "pxe-{{ item['name'] }}.ji2"
      dest: "{{ pxe_dir }}/pxelinux.cfg/{{ item['name'] }}"
      owner: root
      group: root
      mode: 0644
      setype: tftpdir_t
    # add { name: default } to create main menu file
    loop: "{{ os + [{'name':'default'}] }}"
  - name: "Create kickstart file for each distribution major release"
    tags: kickstart
    template:
      src: "kickstart-{{ item[0]['name'] }}.ji2"
      dest: "{{ http['dir'] }}/{{ item[0]['name'] }}/kickstart-{{ item[1]['version'] }}"
      owner: root
      group: root
      mode: 0644
      setype: tftpdir_t
    # no kickstart for solaris
    loop: "{{ os | selectattr('name','ne','solaris') | list | subelements('release') }}"
